name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yml
          delete-other-labels: false
